// <auto-generated />
namespace MyshopDataccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class GetMyOrderDetails2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GetMyOrderDetails2));
        
        string IMigrationMetadata.Id
        {
            get { return "202111150749127_GetMyOrderDetails2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
